### ISSUE TITLE
PlotlyFig examples - use matminer data sets?

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer_examples#3]
@ardunn @albalu 

Should the PlotlyFig examples use the matminer example data sets?

- They are just as easy to load as sklearn data sets
- They would be more relevant / interesting to materials scientists than plotting boston housing prices or something

**Comment by albalu** [comment]
We are mostly using matminer example data sets except:
1) 1 simple plot for each example to make sure data format is clear (e.g. pf.xy(([1, 2], [2, 4])) )
2) that one example where I used boston because I couldn't make heatmap_df look nice with our datasets
I can try harder to make a nice looking example for heatmap_df using our dbs instead of boston. For now, please feel free to take it out if that's the only example making matminer_examples dependent on sklearn.

**Comment by computron** [comment]
@albalu I didn't look carefully, I guess the first example I clicked was the Boston one and I assumed they were all like that.

I'll leave this issue open, I do think you should

* delete the Boston function - the simple data functions are good enough and the Boston one doesn't really help you understand more.

* add one based on a materials data set. You might have to have the "z" value be an average. For example, "x" might be spacegroup number or lattice type, "y" might be nsites, and "z" might be the average of all elastic tensors for materials with that spacegroup/nsites combination.

**Comment by albalu** [comment]
#9 should address this.
